### ISSUE TITLE
Update to bevy 0.14

### ISSUE THREAD

**Issue by davi4046** [PoOnesNerfect/bevy_bsml#2]
I've created a fork that's updated to bevy 0.14: [github.com/davi4046/bevy_bsml](github.com/davi4046/bevy_bsml)

Btw, I've contacted @PoOnesNerfect on Reddit.

**Comment by PoOnesNerfect** [comment]
~I cannot seem to access your fork page. Perhaps it's not public?~
If you would like, could you open a PR to the repo?

nvm, I found it: https://github.com/davi4046/bevy_bsml

**Comment by davi4046** [comment]
Ok, I've made a pull request.
