### ISSUE TITLE
Styling text

### ISSUE THREAD

**Issue by Sorseg** [PoOnesNerfect/bevy_bsml#7]
There is currently no way to provide [TextStyle](https://docs.rs/bevy/0.14.1/bevy/text/struct.TextStyle.html) when creating text nodes and amending the style after the nodes have been creates is quite tedious.

My use case is specifically updating fonts.

It would be a great help if there was some way to pass the text style to the macro.

Thank you for this project, it really cuts down on the boilerplate! :orange_heart:

**Comment by PoOnesNerfect** [comment]
I'm glad you're finding the project useful!

Providing font is very high up on the list of todos. I'll get to it soon.

**Comment by PoOnesNerfect** [comment]
Just pushed `v0.14.9` which adds a new class `FontHandle`.

Now, you can provide font for the text by calling the function `font(Handle<Font>)`.

Hope this resolves your issue! Please let me know if you find any other issues.
